from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.card_metadata_with_file_data import CardMetadataWithFileData
from openapi_server import util

from openapi_server.models.card_metadata_with_file_data import CardMetadataWithFileData  # noqa: E501

class BookmarkCards(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, metadata=None):  # noqa: E501
        """BookmarkCards - a model defined in OpenAPI

        :param metadata: The metadata of this BookmarkCards.  # noqa: E501
        :type metadata: List[CardMetadataWithFileData]
        """
        self.openapi_types = {
            'metadata': List[CardMetadataWithFileData]
        }

        self.attribute_map = {
            'metadata': 'metadata'
        }

        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> 'BookmarkCards':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BookmarkCards of this BookmarkCards.  # noqa: E501
        :rtype: BookmarkCards
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> List[CardMetadataWithFileData]:
        """Gets the metadata of this BookmarkCards.


        :return: The metadata of this BookmarkCards.
        :rtype: List[CardMetadataWithFileData]
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: List[CardMetadataWithFileData]):
        """Sets the metadata of this BookmarkCards.


        :param metadata: The metadata of this BookmarkCards.
        :type metadata: List[CardMetadataWithFileData]
        """
        if metadata is None:
            raise ValueError("Invalid value for `metadata`, must not be `None`")  # noqa: E501

        self._metadata = metadata
