from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class CardMetadata(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, author_id=None, card_html=None, content=None, created_at=None, dataset_id=None, id=None, link=None, metadata=None, private=None, qdrant_point_id=None, tag_set=None, time_stamp=None, tracking_id=None, updated_at=None):  # noqa: E501
        """CardMetadata - a model defined in OpenAPI

        :param author_id: The author_id of this CardMetadata.  # noqa: E501
        :type author_id: str
        :param card_html: The card_html of this CardMetadata.  # noqa: E501
        :type card_html: str
        :param content: The content of this CardMetadata.  # noqa: E501
        :type content: str
        :param created_at: The created_at of this CardMetadata.  # noqa: E501
        :type created_at: datetime
        :param dataset_id: The dataset_id of this CardMetadata.  # noqa: E501
        :type dataset_id: str
        :param id: The id of this CardMetadata.  # noqa: E501
        :type id: str
        :param link: The link of this CardMetadata.  # noqa: E501
        :type link: str
        :param metadata: The metadata of this CardMetadata.  # noqa: E501
        :type metadata: object
        :param private: The private of this CardMetadata.  # noqa: E501
        :type private: bool
        :param qdrant_point_id: The qdrant_point_id of this CardMetadata.  # noqa: E501
        :type qdrant_point_id: str
        :param tag_set: The tag_set of this CardMetadata.  # noqa: E501
        :type tag_set: str
        :param time_stamp: The time_stamp of this CardMetadata.  # noqa: E501
        :type time_stamp: datetime
        :param tracking_id: The tracking_id of this CardMetadata.  # noqa: E501
        :type tracking_id: str
        :param updated_at: The updated_at of this CardMetadata.  # noqa: E501
        :type updated_at: datetime
        """
        self.openapi_types = {
            'author_id': str,
            'card_html': str,
            'content': str,
            'created_at': datetime,
            'dataset_id': str,
            'id': str,
            'link': str,
            'metadata': object,
            'private': bool,
            'qdrant_point_id': str,
            'tag_set': str,
            'time_stamp': datetime,
            'tracking_id': str,
            'updated_at': datetime
        }

        self.attribute_map = {
            'author_id': 'author_id',
            'card_html': 'card_html',
            'content': 'content',
            'created_at': 'created_at',
            'dataset_id': 'dataset_id',
            'id': 'id',
            'link': 'link',
            'metadata': 'metadata',
            'private': 'private',
            'qdrant_point_id': 'qdrant_point_id',
            'tag_set': 'tag_set',
            'time_stamp': 'time_stamp',
            'tracking_id': 'tracking_id',
            'updated_at': 'updated_at'
        }

        self._author_id = author_id
        self._card_html = card_html
        self._content = content
        self._created_at = created_at
        self._dataset_id = dataset_id
        self._id = id
        self._link = link
        self._metadata = metadata
        self._private = private
        self._qdrant_point_id = qdrant_point_id
        self._tag_set = tag_set
        self._time_stamp = time_stamp
        self._tracking_id = tracking_id
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'CardMetadata':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CardMetadata of this CardMetadata.  # noqa: E501
        :rtype: CardMetadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def author_id(self) -> str:
        """Gets the author_id of this CardMetadata.


        :return: The author_id of this CardMetadata.
        :rtype: str
        """
        return self._author_id

    @author_id.setter
    def author_id(self, author_id: str):
        """Sets the author_id of this CardMetadata.


        :param author_id: The author_id of this CardMetadata.
        :type author_id: str
        """
        if author_id is None:
            raise ValueError("Invalid value for `author_id`, must not be `None`")  # noqa: E501

        self._author_id = author_id

    @property
    def card_html(self) -> str:
        """Gets the card_html of this CardMetadata.


        :return: The card_html of this CardMetadata.
        :rtype: str
        """
        return self._card_html

    @card_html.setter
    def card_html(self, card_html: str):
        """Sets the card_html of this CardMetadata.


        :param card_html: The card_html of this CardMetadata.
        :type card_html: str
        """

        self._card_html = card_html

    @property
    def content(self) -> str:
        """Gets the content of this CardMetadata.


        :return: The content of this CardMetadata.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content: str):
        """Sets the content of this CardMetadata.


        :param content: The content of this CardMetadata.
        :type content: str
        """
        if content is None:
            raise ValueError("Invalid value for `content`, must not be `None`")  # noqa: E501

        self._content = content

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this CardMetadata.


        :return: The created_at of this CardMetadata.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this CardMetadata.


        :param created_at: The created_at of this CardMetadata.
        :type created_at: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def dataset_id(self) -> str:
        """Gets the dataset_id of this CardMetadata.


        :return: The dataset_id of this CardMetadata.
        :rtype: str
        """
        return self._dataset_id

    @dataset_id.setter
    def dataset_id(self, dataset_id: str):
        """Sets the dataset_id of this CardMetadata.


        :param dataset_id: The dataset_id of this CardMetadata.
        :type dataset_id: str
        """
        if dataset_id is None:
            raise ValueError("Invalid value for `dataset_id`, must not be `None`")  # noqa: E501

        self._dataset_id = dataset_id

    @property
    def id(self) -> str:
        """Gets the id of this CardMetadata.


        :return: The id of this CardMetadata.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this CardMetadata.


        :param id: The id of this CardMetadata.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def link(self) -> str:
        """Gets the link of this CardMetadata.


        :return: The link of this CardMetadata.
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link: str):
        """Sets the link of this CardMetadata.


        :param link: The link of this CardMetadata.
        :type link: str
        """

        self._link = link

    @property
    def metadata(self) -> object:
        """Gets the metadata of this CardMetadata.


        :return: The metadata of this CardMetadata.
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: object):
        """Sets the metadata of this CardMetadata.


        :param metadata: The metadata of this CardMetadata.
        :type metadata: object
        """

        self._metadata = metadata

    @property
    def private(self) -> bool:
        """Gets the private of this CardMetadata.


        :return: The private of this CardMetadata.
        :rtype: bool
        """
        return self._private

    @private.setter
    def private(self, private: bool):
        """Sets the private of this CardMetadata.


        :param private: The private of this CardMetadata.
        :type private: bool
        """
        if private is None:
            raise ValueError("Invalid value for `private`, must not be `None`")  # noqa: E501

        self._private = private

    @property
    def qdrant_point_id(self) -> str:
        """Gets the qdrant_point_id of this CardMetadata.


        :return: The qdrant_point_id of this CardMetadata.
        :rtype: str
        """
        return self._qdrant_point_id

    @qdrant_point_id.setter
    def qdrant_point_id(self, qdrant_point_id: str):
        """Sets the qdrant_point_id of this CardMetadata.


        :param qdrant_point_id: The qdrant_point_id of this CardMetadata.
        :type qdrant_point_id: str
        """

        self._qdrant_point_id = qdrant_point_id

    @property
    def tag_set(self) -> str:
        """Gets the tag_set of this CardMetadata.


        :return: The tag_set of this CardMetadata.
        :rtype: str
        """
        return self._tag_set

    @tag_set.setter
    def tag_set(self, tag_set: str):
        """Sets the tag_set of this CardMetadata.


        :param tag_set: The tag_set of this CardMetadata.
        :type tag_set: str
        """

        self._tag_set = tag_set

    @property
    def time_stamp(self) -> datetime:
        """Gets the time_stamp of this CardMetadata.


        :return: The time_stamp of this CardMetadata.
        :rtype: datetime
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp: datetime):
        """Sets the time_stamp of this CardMetadata.


        :param time_stamp: The time_stamp of this CardMetadata.
        :type time_stamp: datetime
        """

        self._time_stamp = time_stamp

    @property
    def tracking_id(self) -> str:
        """Gets the tracking_id of this CardMetadata.


        :return: The tracking_id of this CardMetadata.
        :rtype: str
        """
        return self._tracking_id

    @tracking_id.setter
    def tracking_id(self, tracking_id: str):
        """Sets the tracking_id of this CardMetadata.


        :param tracking_id: The tracking_id of this CardMetadata.
        :type tracking_id: str
        """

        self._tracking_id = tracking_id

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this CardMetadata.


        :return: The updated_at of this CardMetadata.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this CardMetadata.


        :param updated_at: The updated_at of this CardMetadata.
        :type updated_at: datetime
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at
