from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class CreateOrganizationData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, configuration=None, name=None):  # noqa: E501
        """CreateOrganizationData - a model defined in OpenAPI

        :param configuration: The configuration of this CreateOrganizationData.  # noqa: E501
        :type configuration: object
        :param name: The name of this CreateOrganizationData.  # noqa: E501
        :type name: str
        """
        self.openapi_types = {
            'configuration': object,
            'name': str
        }

        self.attribute_map = {
            'configuration': 'configuration',
            'name': 'name'
        }

        self._configuration = configuration
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'CreateOrganizationData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateOrganizationData of this CreateOrganizationData.  # noqa: E501
        :rtype: CreateOrganizationData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def configuration(self) -> object:
        """Gets the configuration of this CreateOrganizationData.


        :return: The configuration of this CreateOrganizationData.
        :rtype: object
        """
        return self._configuration

    @configuration.setter
    def configuration(self, configuration: object):
        """Sets the configuration of this CreateOrganizationData.


        :param configuration: The configuration of this CreateOrganizationData.
        :type configuration: object
        """
        if configuration is None:
            raise ValueError("Invalid value for `configuration`, must not be `None`")  # noqa: E501

        self._configuration = configuration

    @property
    def name(self) -> str:
        """Gets the name of this CreateOrganizationData.


        :return: The name of this CreateOrganizationData.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this CreateOrganizationData.


        :param name: The name of this CreateOrganizationData.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name
