from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class CreateCardData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, card_html=None, card_vector=None, collection_id=None, file_uuid=None, link=None, metadata=None, private=None, tag_set=None, time_stamp=None, tracking_id=None):  # noqa: E501
        """CreateCardData - a model defined in OpenAPI

        :param card_html: The card_html of this CreateCardData.  # noqa: E501
        :type card_html: str
        :param card_vector: The card_vector of this CreateCardData.  # noqa: E501
        :type card_vector: List[float]
        :param collection_id: The collection_id of this CreateCardData.  # noqa: E501
        :type collection_id: str
        :param file_uuid: The file_uuid of this CreateCardData.  # noqa: E501
        :type file_uuid: str
        :param link: The link of this CreateCardData.  # noqa: E501
        :type link: str
        :param metadata: The metadata of this CreateCardData.  # noqa: E501
        :type metadata: object
        :param private: The private of this CreateCardData.  # noqa: E501
        :type private: bool
        :param tag_set: The tag_set of this CreateCardData.  # noqa: E501
        :type tag_set: str
        :param time_stamp: The time_stamp of this CreateCardData.  # noqa: E501
        :type time_stamp: str
        :param tracking_id: The tracking_id of this CreateCardData.  # noqa: E501
        :type tracking_id: str
        """
        self.openapi_types = {
            'card_html': str,
            'card_vector': List[float],
            'collection_id': str,
            'file_uuid': str,
            'link': str,
            'metadata': object,
            'private': bool,
            'tag_set': str,
            'time_stamp': str,
            'tracking_id': str
        }

        self.attribute_map = {
            'card_html': 'card_html',
            'card_vector': 'card_vector',
            'collection_id': 'collection_id',
            'file_uuid': 'file_uuid',
            'link': 'link',
            'metadata': 'metadata',
            'private': 'private',
            'tag_set': 'tag_set',
            'time_stamp': 'time_stamp',
            'tracking_id': 'tracking_id'
        }

        self._card_html = card_html
        self._card_vector = card_vector
        self._collection_id = collection_id
        self._file_uuid = file_uuid
        self._link = link
        self._metadata = metadata
        self._private = private
        self._tag_set = tag_set
        self._time_stamp = time_stamp
        self._tracking_id = tracking_id

    @classmethod
    def from_dict(cls, dikt) -> 'CreateCardData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateCardData of this CreateCardData.  # noqa: E501
        :rtype: CreateCardData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def card_html(self) -> str:
        """Gets the card_html of this CreateCardData.


        :return: The card_html of this CreateCardData.
        :rtype: str
        """
        return self._card_html

    @card_html.setter
    def card_html(self, card_html: str):
        """Sets the card_html of this CreateCardData.


        :param card_html: The card_html of this CreateCardData.
        :type card_html: str
        """

        self._card_html = card_html

    @property
    def card_vector(self) -> List[float]:
        """Gets the card_vector of this CreateCardData.


        :return: The card_vector of this CreateCardData.
        :rtype: List[float]
        """
        return self._card_vector

    @card_vector.setter
    def card_vector(self, card_vector: List[float]):
        """Sets the card_vector of this CreateCardData.


        :param card_vector: The card_vector of this CreateCardData.
        :type card_vector: List[float]
        """

        self._card_vector = card_vector

    @property
    def collection_id(self) -> str:
        """Gets the collection_id of this CreateCardData.


        :return: The collection_id of this CreateCardData.
        :rtype: str
        """
        return self._collection_id

    @collection_id.setter
    def collection_id(self, collection_id: str):
        """Sets the collection_id of this CreateCardData.


        :param collection_id: The collection_id of this CreateCardData.
        :type collection_id: str
        """

        self._collection_id = collection_id

    @property
    def file_uuid(self) -> str:
        """Gets the file_uuid of this CreateCardData.


        :return: The file_uuid of this CreateCardData.
        :rtype: str
        """
        return self._file_uuid

    @file_uuid.setter
    def file_uuid(self, file_uuid: str):
        """Sets the file_uuid of this CreateCardData.


        :param file_uuid: The file_uuid of this CreateCardData.
        :type file_uuid: str
        """

        self._file_uuid = file_uuid

    @property
    def link(self) -> str:
        """Gets the link of this CreateCardData.


        :return: The link of this CreateCardData.
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link: str):
        """Sets the link of this CreateCardData.


        :param link: The link of this CreateCardData.
        :type link: str
        """

        self._link = link

    @property
    def metadata(self) -> object:
        """Gets the metadata of this CreateCardData.


        :return: The metadata of this CreateCardData.
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: object):
        """Sets the metadata of this CreateCardData.


        :param metadata: The metadata of this CreateCardData.
        :type metadata: object
        """

        self._metadata = metadata

    @property
    def private(self) -> bool:
        """Gets the private of this CreateCardData.


        :return: The private of this CreateCardData.
        :rtype: bool
        """
        return self._private

    @private.setter
    def private(self, private: bool):
        """Sets the private of this CreateCardData.


        :param private: The private of this CreateCardData.
        :type private: bool
        """

        self._private = private

    @property
    def tag_set(self) -> str:
        """Gets the tag_set of this CreateCardData.


        :return: The tag_set of this CreateCardData.
        :rtype: str
        """
        return self._tag_set

    @tag_set.setter
    def tag_set(self, tag_set: str):
        """Sets the tag_set of this CreateCardData.


        :param tag_set: The tag_set of this CreateCardData.
        :type tag_set: str
        """

        self._tag_set = tag_set

    @property
    def time_stamp(self) -> str:
        """Gets the time_stamp of this CreateCardData.


        :return: The time_stamp of this CreateCardData.
        :rtype: str
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp: str):
        """Sets the time_stamp of this CreateCardData.


        :param time_stamp: The time_stamp of this CreateCardData.
        :type time_stamp: str
        """

        self._time_stamp = time_stamp

    @property
    def tracking_id(self) -> str:
        """Gets the tracking_id of this CreateCardData.


        :return: The tracking_id of this CreateCardData.
        :rtype: str
        """
        return self._tracking_id

    @tracking_id.setter
    def tracking_id(self, tracking_id: str):
        """Sets the tracking_id of this CreateCardData.


        :param tracking_id: The tracking_id of this CreateCardData.
        :type tracking_id: str
        """

        self._tracking_id = tracking_id
