from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class DeleteCollectionData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, collection_id=None):  # noqa: E501
        """DeleteCollectionData - a model defined in OpenAPI

        :param collection_id: The collection_id of this DeleteCollectionData.  # noqa: E501
        :type collection_id: str
        """
        self.openapi_types = {
            'collection_id': str
        }

        self.attribute_map = {
            'collection_id': 'collection_id'
        }

        self._collection_id = collection_id

    @classmethod
    def from_dict(cls, dikt) -> 'DeleteCollectionData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeleteCollectionData of this DeleteCollectionData.  # noqa: E501
        :rtype: DeleteCollectionData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def collection_id(self) -> str:
        """Gets the collection_id of this DeleteCollectionData.


        :return: The collection_id of this DeleteCollectionData.
        :rtype: str
        """
        return self._collection_id

    @collection_id.setter
    def collection_id(self, collection_id: str):
        """Sets the collection_id of this DeleteCollectionData.


        :param collection_id: The collection_id of this DeleteCollectionData.
        :type collection_id: str
        """
        if collection_id is None:
            raise ValueError("Invalid value for `collection_id`, must not be `None`")  # noqa: E501

        self._collection_id = collection_id
