from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class EditMessageData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message_sort_order=None, new_message_content=None, topic_id=None):  # noqa: E501
        """EditMessageData - a model defined in OpenAPI

        :param message_sort_order: The message_sort_order of this EditMessageData.  # noqa: E501
        :type message_sort_order: int
        :param new_message_content: The new_message_content of this EditMessageData.  # noqa: E501
        :type new_message_content: str
        :param topic_id: The topic_id of this EditMessageData.  # noqa: E501
        :type topic_id: str
        """
        self.openapi_types = {
            'message_sort_order': int,
            'new_message_content': str,
            'topic_id': str
        }

        self.attribute_map = {
            'message_sort_order': 'message_sort_order',
            'new_message_content': 'new_message_content',
            'topic_id': 'topic_id'
        }

        self._message_sort_order = message_sort_order
        self._new_message_content = new_message_content
        self._topic_id = topic_id

    @classmethod
    def from_dict(cls, dikt) -> 'EditMessageData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EditMessageData of this EditMessageData.  # noqa: E501
        :rtype: EditMessageData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message_sort_order(self) -> int:
        """Gets the message_sort_order of this EditMessageData.


        :return: The message_sort_order of this EditMessageData.
        :rtype: int
        """
        return self._message_sort_order

    @message_sort_order.setter
    def message_sort_order(self, message_sort_order: int):
        """Sets the message_sort_order of this EditMessageData.


        :param message_sort_order: The message_sort_order of this EditMessageData.
        :type message_sort_order: int
        """
        if message_sort_order is None:
            raise ValueError("Invalid value for `message_sort_order`, must not be `None`")  # noqa: E501

        self._message_sort_order = message_sort_order

    @property
    def new_message_content(self) -> str:
        """Gets the new_message_content of this EditMessageData.


        :return: The new_message_content of this EditMessageData.
        :rtype: str
        """
        return self._new_message_content

    @new_message_content.setter
    def new_message_content(self, new_message_content: str):
        """Sets the new_message_content of this EditMessageData.


        :param new_message_content: The new_message_content of this EditMessageData.
        :type new_message_content: str
        """
        if new_message_content is None:
            raise ValueError("Invalid value for `new_message_content`, must not be `None`")  # noqa: E501

        self._new_message_content = new_message_content

    @property
    def topic_id(self) -> str:
        """Gets the topic_id of this EditMessageData.


        :return: The topic_id of this EditMessageData.
        :rtype: str
        """
        return self._topic_id

    @topic_id.setter
    def topic_id(self, topic_id: str):
        """Sets the topic_id of this EditMessageData.


        :param topic_id: The topic_id of this EditMessageData.
        :type topic_id: str
        """
        if topic_id is None:
            raise ValueError("Invalid value for `topic_id`, must not be `None`")  # noqa: E501

        self._topic_id = topic_id
