from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class File(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, created_at=None, dataset_id=None, file_name=None, id=None, link=None, metadata=None, private=None, size=None, tag_set=None, time_stamp=None, updated_at=None, user_id=None):  # noqa: E501
        """File - a model defined in OpenAPI

        :param created_at: The created_at of this File.  # noqa: E501
        :type created_at: datetime
        :param dataset_id: The dataset_id of this File.  # noqa: E501
        :type dataset_id: str
        :param file_name: The file_name of this File.  # noqa: E501
        :type file_name: str
        :param id: The id of this File.  # noqa: E501
        :type id: str
        :param link: The link of this File.  # noqa: E501
        :type link: str
        :param metadata: The metadata of this File.  # noqa: E501
        :type metadata: object
        :param private: The private of this File.  # noqa: E501
        :type private: bool
        :param size: The size of this File.  # noqa: E501
        :type size: int
        :param tag_set: The tag_set of this File.  # noqa: E501
        :type tag_set: str
        :param time_stamp: The time_stamp of this File.  # noqa: E501
        :type time_stamp: datetime
        :param updated_at: The updated_at of this File.  # noqa: E501
        :type updated_at: datetime
        :param user_id: The user_id of this File.  # noqa: E501
        :type user_id: str
        """
        self.openapi_types = {
            'created_at': datetime,
            'dataset_id': str,
            'file_name': str,
            'id': str,
            'link': str,
            'metadata': object,
            'private': bool,
            'size': int,
            'tag_set': str,
            'time_stamp': datetime,
            'updated_at': datetime,
            'user_id': str
        }

        self.attribute_map = {
            'created_at': 'created_at',
            'dataset_id': 'dataset_id',
            'file_name': 'file_name',
            'id': 'id',
            'link': 'link',
            'metadata': 'metadata',
            'private': 'private',
            'size': 'size',
            'tag_set': 'tag_set',
            'time_stamp': 'time_stamp',
            'updated_at': 'updated_at',
            'user_id': 'user_id'
        }

        self._created_at = created_at
        self._dataset_id = dataset_id
        self._file_name = file_name
        self._id = id
        self._link = link
        self._metadata = metadata
        self._private = private
        self._size = size
        self._tag_set = tag_set
        self._time_stamp = time_stamp
        self._updated_at = updated_at
        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'File':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The File of this File.  # noqa: E501
        :rtype: File
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this File.


        :return: The created_at of this File.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this File.


        :param created_at: The created_at of this File.
        :type created_at: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def dataset_id(self) -> str:
        """Gets the dataset_id of this File.


        :return: The dataset_id of this File.
        :rtype: str
        """
        return self._dataset_id

    @dataset_id.setter
    def dataset_id(self, dataset_id: str):
        """Sets the dataset_id of this File.


        :param dataset_id: The dataset_id of this File.
        :type dataset_id: str
        """
        if dataset_id is None:
            raise ValueError("Invalid value for `dataset_id`, must not be `None`")  # noqa: E501

        self._dataset_id = dataset_id

    @property
    def file_name(self) -> str:
        """Gets the file_name of this File.


        :return: The file_name of this File.
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name: str):
        """Sets the file_name of this File.


        :param file_name: The file_name of this File.
        :type file_name: str
        """
        if file_name is None:
            raise ValueError("Invalid value for `file_name`, must not be `None`")  # noqa: E501

        self._file_name = file_name

    @property
    def id(self) -> str:
        """Gets the id of this File.


        :return: The id of this File.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this File.


        :param id: The id of this File.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def link(self) -> str:
        """Gets the link of this File.


        :return: The link of this File.
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link: str):
        """Sets the link of this File.


        :param link: The link of this File.
        :type link: str
        """

        self._link = link

    @property
    def metadata(self) -> object:
        """Gets the metadata of this File.


        :return: The metadata of this File.
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: object):
        """Sets the metadata of this File.


        :param metadata: The metadata of this File.
        :type metadata: object
        """

        self._metadata = metadata

    @property
    def private(self) -> bool:
        """Gets the private of this File.


        :return: The private of this File.
        :rtype: bool
        """
        return self._private

    @private.setter
    def private(self, private: bool):
        """Sets the private of this File.


        :param private: The private of this File.
        :type private: bool
        """
        if private is None:
            raise ValueError("Invalid value for `private`, must not be `None`")  # noqa: E501

        self._private = private

    @property
    def size(self) -> int:
        """Gets the size of this File.


        :return: The size of this File.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size: int):
        """Sets the size of this File.


        :param size: The size of this File.
        :type size: int
        """
        if size is None:
            raise ValueError("Invalid value for `size`, must not be `None`")  # noqa: E501

        self._size = size

    @property
    def tag_set(self) -> str:
        """Gets the tag_set of this File.


        :return: The tag_set of this File.
        :rtype: str
        """
        return self._tag_set

    @tag_set.setter
    def tag_set(self, tag_set: str):
        """Sets the tag_set of this File.


        :param tag_set: The tag_set of this File.
        :type tag_set: str
        """

        self._tag_set = tag_set

    @property
    def time_stamp(self) -> datetime:
        """Gets the time_stamp of this File.


        :return: The time_stamp of this File.
        :rtype: datetime
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp: datetime):
        """Sets the time_stamp of this File.


        :param time_stamp: The time_stamp of this File.
        :type time_stamp: datetime
        """

        self._time_stamp = time_stamp

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this File.


        :return: The updated_at of this File.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this File.


        :param updated_at: The updated_at of this File.
        :type updated_at: datetime
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at

    @property
    def user_id(self) -> str:
        """Gets the user_id of this File.


        :return: The user_id of this File.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this File.


        :param user_id: The user_id of this File.
        :type user_id: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id
