from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class FileDTO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, base64url_content=None, created_at=None, file_name=None, id=None, link=None, metadata=None, private=None, size=None, updated_at=None, user_id=None):  # noqa: E501
        """FileDTO - a model defined in OpenAPI

        :param base64url_content: The base64url_content of this FileDTO.  # noqa: E501
        :type base64url_content: str
        :param created_at: The created_at of this FileDTO.  # noqa: E501
        :type created_at: datetime
        :param file_name: The file_name of this FileDTO.  # noqa: E501
        :type file_name: str
        :param id: The id of this FileDTO.  # noqa: E501
        :type id: str
        :param link: The link of this FileDTO.  # noqa: E501
        :type link: str
        :param metadata: The metadata of this FileDTO.  # noqa: E501
        :type metadata: object
        :param private: The private of this FileDTO.  # noqa: E501
        :type private: bool
        :param size: The size of this FileDTO.  # noqa: E501
        :type size: int
        :param updated_at: The updated_at of this FileDTO.  # noqa: E501
        :type updated_at: datetime
        :param user_id: The user_id of this FileDTO.  # noqa: E501
        :type user_id: str
        """
        self.openapi_types = {
            'base64url_content': str,
            'created_at': datetime,
            'file_name': str,
            'id': str,
            'link': str,
            'metadata': object,
            'private': bool,
            'size': int,
            'updated_at': datetime,
            'user_id': str
        }

        self.attribute_map = {
            'base64url_content': 'base64url_content',
            'created_at': 'created_at',
            'file_name': 'file_name',
            'id': 'id',
            'link': 'link',
            'metadata': 'metadata',
            'private': 'private',
            'size': 'size',
            'updated_at': 'updated_at',
            'user_id': 'user_id'
        }

        self._base64url_content = base64url_content
        self._created_at = created_at
        self._file_name = file_name
        self._id = id
        self._link = link
        self._metadata = metadata
        self._private = private
        self._size = size
        self._updated_at = updated_at
        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'FileDTO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FileDTO of this FileDTO.  # noqa: E501
        :rtype: FileDTO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def base64url_content(self) -> str:
        """Gets the base64url_content of this FileDTO.


        :return: The base64url_content of this FileDTO.
        :rtype: str
        """
        return self._base64url_content

    @base64url_content.setter
    def base64url_content(self, base64url_content: str):
        """Sets the base64url_content of this FileDTO.


        :param base64url_content: The base64url_content of this FileDTO.
        :type base64url_content: str
        """
        if base64url_content is None:
            raise ValueError("Invalid value for `base64url_content`, must not be `None`")  # noqa: E501

        self._base64url_content = base64url_content

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this FileDTO.


        :return: The created_at of this FileDTO.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this FileDTO.


        :param created_at: The created_at of this FileDTO.
        :type created_at: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def file_name(self) -> str:
        """Gets the file_name of this FileDTO.


        :return: The file_name of this FileDTO.
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name: str):
        """Sets the file_name of this FileDTO.


        :param file_name: The file_name of this FileDTO.
        :type file_name: str
        """
        if file_name is None:
            raise ValueError("Invalid value for `file_name`, must not be `None`")  # noqa: E501

        self._file_name = file_name

    @property
    def id(self) -> str:
        """Gets the id of this FileDTO.


        :return: The id of this FileDTO.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this FileDTO.


        :param id: The id of this FileDTO.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def link(self) -> str:
        """Gets the link of this FileDTO.


        :return: The link of this FileDTO.
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link: str):
        """Sets the link of this FileDTO.


        :param link: The link of this FileDTO.
        :type link: str
        """

        self._link = link

    @property
    def metadata(self) -> object:
        """Gets the metadata of this FileDTO.


        :return: The metadata of this FileDTO.
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: object):
        """Sets the metadata of this FileDTO.


        :param metadata: The metadata of this FileDTO.
        :type metadata: object
        """

        self._metadata = metadata

    @property
    def private(self) -> bool:
        """Gets the private of this FileDTO.


        :return: The private of this FileDTO.
        :rtype: bool
        """
        return self._private

    @private.setter
    def private(self, private: bool):
        """Sets the private of this FileDTO.


        :param private: The private of this FileDTO.
        :type private: bool
        """
        if private is None:
            raise ValueError("Invalid value for `private`, must not be `None`")  # noqa: E501

        self._private = private

    @property
    def size(self) -> int:
        """Gets the size of this FileDTO.


        :return: The size of this FileDTO.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size: int):
        """Sets the size of this FileDTO.


        :param size: The size of this FileDTO.
        :type size: int
        """
        if size is None:
            raise ValueError("Invalid value for `size`, must not be `None`")  # noqa: E501

        self._size = size

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this FileDTO.


        :return: The updated_at of this FileDTO.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this FileDTO.


        :param updated_at: The updated_at of this FileDTO.
        :type updated_at: datetime
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at

    @property
    def user_id(self) -> str:
        """Gets the user_id of this FileDTO.


        :return: The user_id of this FileDTO.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this FileDTO.


        :param user_id: The user_id of this FileDTO.
        :type user_id: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id
