from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.chat_message_proxy import ChatMessageProxy
from openapi_server import util

from openapi_server.models.chat_message_proxy import ChatMessageProxy  # noqa: E501

class GenerateCardsRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, card_ids=None, prev_messages=None):  # noqa: E501
        """GenerateCardsRequest - a model defined in OpenAPI

        :param card_ids: The card_ids of this GenerateCardsRequest.  # noqa: E501
        :type card_ids: List[str]
        :param prev_messages: The prev_messages of this GenerateCardsRequest.  # noqa: E501
        :type prev_messages: List[ChatMessageProxy]
        """
        self.openapi_types = {
            'card_ids': List[str],
            'prev_messages': List[ChatMessageProxy]
        }

        self.attribute_map = {
            'card_ids': 'card_ids',
            'prev_messages': 'prev_messages'
        }

        self._card_ids = card_ids
        self._prev_messages = prev_messages

    @classmethod
    def from_dict(cls, dikt) -> 'GenerateCardsRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GenerateCardsRequest of this GenerateCardsRequest.  # noqa: E501
        :rtype: GenerateCardsRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def card_ids(self) -> List[str]:
        """Gets the card_ids of this GenerateCardsRequest.


        :return: The card_ids of this GenerateCardsRequest.
        :rtype: List[str]
        """
        return self._card_ids

    @card_ids.setter
    def card_ids(self, card_ids: List[str]):
        """Sets the card_ids of this GenerateCardsRequest.


        :param card_ids: The card_ids of this GenerateCardsRequest.
        :type card_ids: List[str]
        """
        if card_ids is None:
            raise ValueError("Invalid value for `card_ids`, must not be `None`")  # noqa: E501

        self._card_ids = card_ids

    @property
    def prev_messages(self) -> List[ChatMessageProxy]:
        """Gets the prev_messages of this GenerateCardsRequest.


        :return: The prev_messages of this GenerateCardsRequest.
        :rtype: List[ChatMessageProxy]
        """
        return self._prev_messages

    @prev_messages.setter
    def prev_messages(self, prev_messages: List[ChatMessageProxy]):
        """Sets the prev_messages of this GenerateCardsRequest.


        :param prev_messages: The prev_messages of this GenerateCardsRequest.
        :type prev_messages: List[ChatMessageProxy]
        """
        if prev_messages is None:
            raise ValueError("Invalid value for `prev_messages`, must not be `None`")  # noqa: E501

        self._prev_messages = prev_messages
