from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GetUserWithCardsData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, page=None, user_id=None):  # noqa: E501
        """GetUserWithCardsData - a model defined in OpenAPI

        :param page: The page of this GetUserWithCardsData.  # noqa: E501
        :type page: int
        :param user_id: The user_id of this GetUserWithCardsData.  # noqa: E501
        :type user_id: str
        """
        self.openapi_types = {
            'page': int,
            'user_id': str
        }

        self.attribute_map = {
            'page': 'page',
            'user_id': 'user_id'
        }

        self._page = page
        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'GetUserWithCardsData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetUserWithCardsData of this GetUserWithCardsData.  # noqa: E501
        :rtype: GetUserWithCardsData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def page(self) -> int:
        """Gets the page of this GetUserWithCardsData.


        :return: The page of this GetUserWithCardsData.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page: int):
        """Sets the page of this GetUserWithCardsData.


        :param page: The page of this GetUserWithCardsData.
        :type page: int
        """
        if page is None:
            raise ValueError("Invalid value for `page`, must not be `None`")  # noqa: E501

        self._page = page

    @property
    def user_id(self) -> str:
        """Gets the user_id of this GetUserWithCardsData.


        :return: The user_id of this GetUserWithCardsData.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this GetUserWithCardsData.


        :param user_id: The user_id of this GetUserWithCardsData.
        :type user_id: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id
