from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GetAllBookmarksData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, collection_id=None, page=None):  # noqa: E501
        """GetAllBookmarksData - a model defined in OpenAPI

        :param collection_id: The collection_id of this GetAllBookmarksData.  # noqa: E501
        :type collection_id: str
        :param page: The page of this GetAllBookmarksData.  # noqa: E501
        :type page: int
        """
        self.openapi_types = {
            'collection_id': str,
            'page': int
        }

        self.attribute_map = {
            'collection_id': 'collection_id',
            'page': 'page'
        }

        self._collection_id = collection_id
        self._page = page

    @classmethod
    def from_dict(cls, dikt) -> 'GetAllBookmarksData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetAllBookmarksData of this GetAllBookmarksData.  # noqa: E501
        :rtype: GetAllBookmarksData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def collection_id(self) -> str:
        """Gets the collection_id of this GetAllBookmarksData.


        :return: The collection_id of this GetAllBookmarksData.
        :rtype: str
        """
        return self._collection_id

    @collection_id.setter
    def collection_id(self, collection_id: str):
        """Sets the collection_id of this GetAllBookmarksData.


        :param collection_id: The collection_id of this GetAllBookmarksData.
        :type collection_id: str
        """
        if collection_id is None:
            raise ValueError("Invalid value for `collection_id`, must not be `None`")  # noqa: E501

        self._collection_id = collection_id

    @property
    def page(self) -> int:
        """Gets the page of this GetAllBookmarksData.


        :return: The page of this GetAllBookmarksData.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page: int):
        """Sets the page of this GetAllBookmarksData.


        :param page: The page of this GetAllBookmarksData.
        :type page: int
        """
        if page is not None and page < 0:  # noqa: E501
            raise ValueError("Invalid value for `page`, must be a value greater than or equal to `0`")  # noqa: E501

        self._page = page
