from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class NotificationId(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, notification_id=None):  # noqa: E501
        """NotificationId - a model defined in OpenAPI

        :param notification_id: The notification_id of this NotificationId.  # noqa: E501
        :type notification_id: str
        """
        self.openapi_types = {
            'notification_id': str
        }

        self.attribute_map = {
            'notification_id': 'notification_id'
        }

        self._notification_id = notification_id

    @classmethod
    def from_dict(cls, dikt) -> 'NotificationId':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NotificationId of this NotificationId.  # noqa: E501
        :rtype: NotificationId
        """
        return util.deserialize_model(dikt, cls)

    @property
    def notification_id(self) -> str:
        """Gets the notification_id of this NotificationId.


        :return: The notification_id of this NotificationId.
        :rtype: str
        """
        return self._notification_id

    @notification_id.setter
    def notification_id(self, notification_id: str):
        """Sets the notification_id of this NotificationId.


        :param notification_id: The notification_id of this NotificationId.
        :type notification_id: str
        """
        if notification_id is None:
            raise ValueError("Invalid value for `notification_id`, must not be `None`")  # noqa: E501

        self._notification_id = notification_id
