from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class RegenerateMessageData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, topic_id=None):  # noqa: E501
        """RegenerateMessageData - a model defined in OpenAPI

        :param topic_id: The topic_id of this RegenerateMessageData.  # noqa: E501
        :type topic_id: str
        """
        self.openapi_types = {
            'topic_id': str
        }

        self.attribute_map = {
            'topic_id': 'topic_id'
        }

        self._topic_id = topic_id

    @classmethod
    def from_dict(cls, dikt) -> 'RegenerateMessageData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RegenerateMessageData of this RegenerateMessageData.  # noqa: E501
        :rtype: RegenerateMessageData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def topic_id(self) -> str:
        """Gets the topic_id of this RegenerateMessageData.


        :return: The topic_id of this RegenerateMessageData.
        :rtype: str
        """
        return self._topic_id

    @topic_id.setter
    def topic_id(self, topic_id: str):
        """Sets the topic_id of this RegenerateMessageData.


        :param topic_id: The topic_id of this RegenerateMessageData.
        :type topic_id: str
        """
        if topic_id is None:
            raise ValueError("Invalid value for `topic_id`, must not be `None`")  # noqa: E501

        self._topic_id = topic_id
