from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class SetUserApiKeyResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, api_key=None):  # noqa: E501
        """SetUserApiKeyResponse - a model defined in OpenAPI

        :param api_key: The api_key of this SetUserApiKeyResponse.  # noqa: E501
        :type api_key: str
        """
        self.openapi_types = {
            'api_key': str
        }

        self.attribute_map = {
            'api_key': 'api_key'
        }

        self._api_key = api_key

    @classmethod
    def from_dict(cls, dikt) -> 'SetUserApiKeyResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SetUserApiKeyResponse of this SetUserApiKeyResponse.  # noqa: E501
        :rtype: SetUserApiKeyResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def api_key(self) -> str:
        """Gets the api_key of this SetUserApiKeyResponse.


        :return: The api_key of this SetUserApiKeyResponse.
        :rtype: str
        """
        return self._api_key

    @api_key.setter
    def api_key(self, api_key: str):
        """Sets the api_key of this SetUserApiKeyResponse.


        :param api_key: The api_key of this SetUserApiKeyResponse.
        :type api_key: str
        """
        if api_key is None:
            raise ValueError("Invalid value for `api_key`, must not be `None`")  # noqa: E501

        self._api_key = api_key
