from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class SuggestedQueriesRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, query=None):  # noqa: E501
        """SuggestedQueriesRequest - a model defined in OpenAPI

        :param query: The query of this SuggestedQueriesRequest.  # noqa: E501
        :type query: str
        """
        self.openapi_types = {
            'query': str
        }

        self.attribute_map = {
            'query': 'query'
        }

        self._query = query

    @classmethod
    def from_dict(cls, dikt) -> 'SuggestedQueriesRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SuggestedQueriesRequest of this SuggestedQueriesRequest.  # noqa: E501
        :rtype: SuggestedQueriesRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def query(self) -> str:
        """Gets the query of this SuggestedQueriesRequest.


        :return: The query of this SuggestedQueriesRequest.
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query: str):
        """Sets the query of this SuggestedQueriesRequest.


        :param query: The query of this SuggestedQueriesRequest.
        :type query: str
        """
        if query is None:
            raise ValueError("Invalid value for `query`, must not be `None`")  # noqa: E501

        self._query = query
