from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class SuggestedQueriesResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, queries=None):  # noqa: E501
        """SuggestedQueriesResponse - a model defined in OpenAPI

        :param queries: The queries of this SuggestedQueriesResponse.  # noqa: E501
        :type queries: List[str]
        """
        self.openapi_types = {
            'queries': List[str]
        }

        self.attribute_map = {
            'queries': 'queries'
        }

        self._queries = queries

    @classmethod
    def from_dict(cls, dikt) -> 'SuggestedQueriesResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SuggestedQueriesResponse of this SuggestedQueriesResponse.  # noqa: E501
        :rtype: SuggestedQueriesResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def queries(self) -> List[str]:
        """Gets the queries of this SuggestedQueriesResponse.


        :return: The queries of this SuggestedQueriesResponse.
        :rtype: List[str]
        """
        return self._queries

    @queries.setter
    def queries(self, queries: List[str]):
        """Sets the queries of this SuggestedQueriesResponse.


        :param queries: The queries of this SuggestedQueriesResponse.
        :type queries: List[str]
        """
        if queries is None:
            raise ValueError("Invalid value for `queries`, must not be `None`")  # noqa: E501

        self._queries = queries
