from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class UpdateCardCollectionData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, collection_id=None, description=None, is_public=None, name=None):  # noqa: E501
        """UpdateCardCollectionData - a model defined in OpenAPI

        :param collection_id: The collection_id of this UpdateCardCollectionData.  # noqa: E501
        :type collection_id: str
        :param description: The description of this UpdateCardCollectionData.  # noqa: E501
        :type description: str
        :param is_public: The is_public of this UpdateCardCollectionData.  # noqa: E501
        :type is_public: bool
        :param name: The name of this UpdateCardCollectionData.  # noqa: E501
        :type name: str
        """
        self.openapi_types = {
            'collection_id': str,
            'description': str,
            'is_public': bool,
            'name': str
        }

        self.attribute_map = {
            'collection_id': 'collection_id',
            'description': 'description',
            'is_public': 'is_public',
            'name': 'name'
        }

        self._collection_id = collection_id
        self._description = description
        self._is_public = is_public
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateCardCollectionData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateCardCollectionData of this UpdateCardCollectionData.  # noqa: E501
        :rtype: UpdateCardCollectionData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def collection_id(self) -> str:
        """Gets the collection_id of this UpdateCardCollectionData.


        :return: The collection_id of this UpdateCardCollectionData.
        :rtype: str
        """
        return self._collection_id

    @collection_id.setter
    def collection_id(self, collection_id: str):
        """Sets the collection_id of this UpdateCardCollectionData.


        :param collection_id: The collection_id of this UpdateCardCollectionData.
        :type collection_id: str
        """
        if collection_id is None:
            raise ValueError("Invalid value for `collection_id`, must not be `None`")  # noqa: E501

        self._collection_id = collection_id

    @property
    def description(self) -> str:
        """Gets the description of this UpdateCardCollectionData.


        :return: The description of this UpdateCardCollectionData.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this UpdateCardCollectionData.


        :param description: The description of this UpdateCardCollectionData.
        :type description: str
        """

        self._description = description

    @property
    def is_public(self) -> bool:
        """Gets the is_public of this UpdateCardCollectionData.


        :return: The is_public of this UpdateCardCollectionData.
        :rtype: bool
        """
        return self._is_public

    @is_public.setter
    def is_public(self, is_public: bool):
        """Sets the is_public of this UpdateCardCollectionData.


        :param is_public: The is_public of this UpdateCardCollectionData.
        :type is_public: bool
        """

        self._is_public = is_public

    @property
    def name(self) -> str:
        """Gets the name of this UpdateCardCollectionData.


        :return: The name of this UpdateCardCollectionData.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this UpdateCardCollectionData.


        :param name: The name of this UpdateCardCollectionData.
        :type name: str
        """

        self._name = name
