from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class UpdateFileData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, file_id=None, private=None):  # noqa: E501
        """UpdateFileData - a model defined in OpenAPI

        :param file_id: The file_id of this UpdateFileData.  # noqa: E501
        :type file_id: str
        :param private: The private of this UpdateFileData.  # noqa: E501
        :type private: bool
        """
        self.openapi_types = {
            'file_id': str,
            'private': bool
        }

        self.attribute_map = {
            'file_id': 'file_id',
            'private': 'private'
        }

        self._file_id = file_id
        self._private = private

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateFileData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateFileData of this UpdateFileData.  # noqa: E501
        :rtype: UpdateFileData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def file_id(self) -> str:
        """Gets the file_id of this UpdateFileData.


        :return: The file_id of this UpdateFileData.
        :rtype: str
        """
        return self._file_id

    @file_id.setter
    def file_id(self, file_id: str):
        """Sets the file_id of this UpdateFileData.


        :param file_id: The file_id of this UpdateFileData.
        :type file_id: str
        """
        if file_id is None:
            raise ValueError("Invalid value for `file_id`, must not be `None`")  # noqa: E501

        self._file_id = file_id

    @property
    def private(self) -> bool:
        """Gets the private of this UpdateFileData.


        :return: The private of this UpdateFileData.
        :rtype: bool
        """
        return self._private

    @private.setter
    def private(self, private: bool):
        """Sets the private of this UpdateFileData.


        :param private: The private of this UpdateFileData.
        :type private: bool
        """
        if private is None:
            raise ValueError("Invalid value for `private`, must not be `None`")  # noqa: E501

        self._private = private
