from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.card_metadata_with_file_data import CardMetadataWithFileData
from openapi_server import util

from openapi_server.models.card_metadata_with_file_data import CardMetadataWithFileData  # noqa: E501

class UserDTOWithCards(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cards=None, created_at=None, email=None, id=None, organization_id=None, total_cards_created=None, username=None, visible_email=None, website=None):  # noqa: E501
        """UserDTOWithCards - a model defined in OpenAPI

        :param cards: The cards of this UserDTOWithCards.  # noqa: E501
        :type cards: List[CardMetadataWithFileData]
        :param created_at: The created_at of this UserDTOWithCards.  # noqa: E501
        :type created_at: datetime
        :param email: The email of this UserDTOWithCards.  # noqa: E501
        :type email: str
        :param id: The id of this UserDTOWithCards.  # noqa: E501
        :type id: str
        :param organization_id: The organization_id of this UserDTOWithCards.  # noqa: E501
        :type organization_id: str
        :param total_cards_created: The total_cards_created of this UserDTOWithCards.  # noqa: E501
        :type total_cards_created: int
        :param username: The username of this UserDTOWithCards.  # noqa: E501
        :type username: str
        :param visible_email: The visible_email of this UserDTOWithCards.  # noqa: E501
        :type visible_email: bool
        :param website: The website of this UserDTOWithCards.  # noqa: E501
        :type website: str
        """
        self.openapi_types = {
            'cards': List[CardMetadataWithFileData],
            'created_at': datetime,
            'email': str,
            'id': str,
            'organization_id': str,
            'total_cards_created': int,
            'username': str,
            'visible_email': bool,
            'website': str
        }

        self.attribute_map = {
            'cards': 'cards',
            'created_at': 'created_at',
            'email': 'email',
            'id': 'id',
            'organization_id': 'organization_id',
            'total_cards_created': 'total_cards_created',
            'username': 'username',
            'visible_email': 'visible_email',
            'website': 'website'
        }

        self._cards = cards
        self._created_at = created_at
        self._email = email
        self._id = id
        self._organization_id = organization_id
        self._total_cards_created = total_cards_created
        self._username = username
        self._visible_email = visible_email
        self._website = website

    @classmethod
    def from_dict(cls, dikt) -> 'UserDTOWithCards':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserDTOWithCards of this UserDTOWithCards.  # noqa: E501
        :rtype: UserDTOWithCards
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cards(self) -> List[CardMetadataWithFileData]:
        """Gets the cards of this UserDTOWithCards.


        :return: The cards of this UserDTOWithCards.
        :rtype: List[CardMetadataWithFileData]
        """
        return self._cards

    @cards.setter
    def cards(self, cards: List[CardMetadataWithFileData]):
        """Sets the cards of this UserDTOWithCards.


        :param cards: The cards of this UserDTOWithCards.
        :type cards: List[CardMetadataWithFileData]
        """
        if cards is None:
            raise ValueError("Invalid value for `cards`, must not be `None`")  # noqa: E501

        self._cards = cards

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this UserDTOWithCards.


        :return: The created_at of this UserDTOWithCards.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this UserDTOWithCards.


        :param created_at: The created_at of this UserDTOWithCards.
        :type created_at: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def email(self) -> str:
        """Gets the email of this UserDTOWithCards.


        :return: The email of this UserDTOWithCards.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this UserDTOWithCards.


        :param email: The email of this UserDTOWithCards.
        :type email: str
        """

        self._email = email

    @property
    def id(self) -> str:
        """Gets the id of this UserDTOWithCards.


        :return: The id of this UserDTOWithCards.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this UserDTOWithCards.


        :param id: The id of this UserDTOWithCards.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def organization_id(self) -> str:
        """Gets the organization_id of this UserDTOWithCards.


        :return: The organization_id of this UserDTOWithCards.
        :rtype: str
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id: str):
        """Sets the organization_id of this UserDTOWithCards.


        :param organization_id: The organization_id of this UserDTOWithCards.
        :type organization_id: str
        """
        if organization_id is None:
            raise ValueError("Invalid value for `organization_id`, must not be `None`")  # noqa: E501

        self._organization_id = organization_id

    @property
    def total_cards_created(self) -> int:
        """Gets the total_cards_created of this UserDTOWithCards.


        :return: The total_cards_created of this UserDTOWithCards.
        :rtype: int
        """
        return self._total_cards_created

    @total_cards_created.setter
    def total_cards_created(self, total_cards_created: int):
        """Sets the total_cards_created of this UserDTOWithCards.


        :param total_cards_created: The total_cards_created of this UserDTOWithCards.
        :type total_cards_created: int
        """
        if total_cards_created is None:
            raise ValueError("Invalid value for `total_cards_created`, must not be `None`")  # noqa: E501

        self._total_cards_created = total_cards_created

    @property
    def username(self) -> str:
        """Gets the username of this UserDTOWithCards.


        :return: The username of this UserDTOWithCards.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this UserDTOWithCards.


        :param username: The username of this UserDTOWithCards.
        :type username: str
        """

        self._username = username

    @property
    def visible_email(self) -> bool:
        """Gets the visible_email of this UserDTOWithCards.


        :return: The visible_email of this UserDTOWithCards.
        :rtype: bool
        """
        return self._visible_email

    @visible_email.setter
    def visible_email(self, visible_email: bool):
        """Sets the visible_email of this UserDTOWithCards.


        :param visible_email: The visible_email of this UserDTOWithCards.
        :type visible_email: bool
        """
        if visible_email is None:
            raise ValueError("Invalid value for `visible_email`, must not be `None`")  # noqa: E501

        self._visible_email = visible_email

    @property
    def website(self) -> str:
        """Gets the website of this UserDTOWithCards.


        :return: The website of this UserDTOWithCards.
        :rtype: str
        """
        return self._website

    @website.setter
    def website(self, website: str):
        """Sets the website of this UserDTOWithCards.


        :param website: The website of this UserDTOWithCards.
        :type website: str
        """

        self._website = website
